# Set the selection tool here:
SelectionTool: 51
# when should the log file be moved to logs/
mb: 5

# Which things would you like to have logged?
DoCommand: true
ChangeWorld: true
ChangeGameMode: true
BlockIgnite: true
IgnoreEnvironment: false
BucketWaterEmpty: true
BucketLavaEmpty: true
ChestChange: false
FurnaceChange: false
EnderManPlaceAndPickup: true
ZombieBreakDoor: true
Explosions: true
SignChangeText: true
PlayerJoin: true

UsePermissions: false