name: GriefLog
version: 3.9
main: tk.blackwolf12333.grieflog.GriefLog
softdepend: [PermissionsEx,Permissions,GroupManager,bPermissions,Vault]
commands:
    glog:
        description: Main command, type glog help for more info.
        usage: /glog <option> <arguments>